blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, SearchView, UserPost
from django.conf import settings
from . import views
from django.conf.urls.static import static


app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('search-blog/', SearchView.as_view(), name='search_blog'),
    path('posts/<username>/', UserPost.as_view(), name='user_posts'),

    path('blog/create/', PostCreateView.as_view(),
         name='blog_create'),
    path('blog/<slug:title_slug>/', PostDetailView.as_view(), name='blog_detail'),

    path('blog/<slug:title_slug>/update/',
         PostUpdateView.as_view(), name='blog_update'),

    path('blog/<slug:title_slug>/delete/',
         PostDeleteView.as_view(), name='blog_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django2/urls.py
from django.conf.urls.static import static
from django.conf import settings
"""django2 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
    path('tinymce/', include('tinymce.urls')),

    path('settings/change-password/', auth_views.PasswordChangeView.as_view(
        template_name='users/change-password.html'), name='password_change'),

    path('settings/change-password-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/change-password-done.html'), name='password_change_done'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password-reset.html',
                                              email_template_name='users/password-reset-email.html',
                                              subject_template_name='users/password-reset-subject.txt'),
         name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password-reset-done.html'),
        name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password-reset-confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password-reset-complete.html'),
        name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.profile_update, name='profile_update'),

]

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'blog:home' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto navbar-default">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:home' %}">Blog</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:blog_create' %}">Post</a>
            </li>
            {% endif %}
            {% if not user.is_authenticated %}
            <div style="position:absolute; right:5%;">
                <a href="{% url 'users:login' %}" class="btn btn-secondary mx-2">Login</a>
                <a href="{% url 'users:signup' %}" class="btn btn-warning">Sign up</a>
            </div>

            {% else %}
            <li class="nav-item dropdown mb-5" style="position:absolute; right:5%;">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <img src="{{ user.profile.image.url }}"
                        style="width:35px; height:35px; border-radius:50%; border:1px solid #f3f3f3; padding:2px;"
                        alt="{{ user.username }} img" class="mb-1">
                    {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a>
                </div>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>

    </div>
</nav>