blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, SearchView, UserPost
from django.conf import settings
from . import views
from django.conf.urls.static import static


app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('search-blog/', SearchView.as_view(), name='search_blog'),
    path('posts/<username>/', UserPost.as_view(), name='user_posts'),

    path('blog/create/', PostCreateView.as_view(),
         name='blog_create'),
    path('blog/<slug:title_slug>/', PostDetailView.as_view(), name='blog_detail'),

    path('blog/<slug:title_slug>/update/',
         PostUpdateView.as_view(), name='blog_update'),

    path('blog/<slug:title_slug>/delete/',
         PostDeleteView.as_view(), name='blog_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django2/urls.py
from django.conf.urls.static import static
from django.conf import settings
"""django2 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
    path('tinymce/', include('tinymce.urls')),

    path('settings/change-password/', auth_views.PasswordChangeView.as_view(
        template_name='users/change-password.html'), name='password_change'),

    path('settings/change-password-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/change-password-done.html'), name='password_change_done'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password-reset.html',
                                              email_template_name='users/password-reset-email.html',
                                              subject_template_name='users/password-reset-subject.txt'),
         name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password-reset-done.html'),
        name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password-reset-confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password-reset-complete.html'),
        name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from tinymce.models import HTMLField
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.conf import settings
User = settings.AUTH_USER_MODEL


class BlogPost(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    slug = models.SlugField(blank=True, unique=True)
    image = models.ImageField(default='default.jpg',
                              upload_to='posts/%Y/%m/%d')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(
        blank=True, null=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # this will order elements on
        ordering = ['-updated_at', '-created_at']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BlogPost, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={'title_slug': self.slug})

    def get_update_url(self):
        return reverse('blog:blog_update', kwargs={'title_slug': self.slug})

    def get_delete_url(self):
        return reverse('blog:blog_delete', kwargs={'title_slug': self.slug})

blog/forms.py
from .models import BlogPost
from django import forms
from tinymce import TinyMCE


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class BlogForm(forms.ModelForm):
    title = forms.CharField()
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 20, 'rows': 10}
        )
    )
    image = forms.ImageField()

    class Meta:
        model = BlogPost
        fields = [
            'title',
            'content',
            'image'
        ]

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import BlogPost
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from .forms import BlogForm
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.utils import timezone
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User


class PostListView(ListView):
    queryset = BlogPost.objects.order_by('-created_at')
    template_name = "blogs/home.html"
    context_object_name = 'queryset'
    ordering = ['-updated_at', '-created_at']
    paginate_by = 3

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*kwargs)
        context['latest_post'] = BlogPost.objects.order_by("-created_at")[:10]
        return context


class PostDetailView(DetailView):
    model = BlogPost
    template_name = 'blogs/blog-detail.html'

    def get_object(self):
        slug = self.kwargs.get('title_slug')
        return get_object_or_404(BlogPost, slug=slug)


class PostCreateView(SuccessMessageMixin, CreateView):
    model = BlogPost
    form_class = BlogForm
    template_name = 'blogs/blog-form.html'
    success_message = 'Post added successfully!'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostUpdateView(SuccessMessageMixin, UpdateView):
    model = BlogPost
    form_class = BlogForm
    template_name = 'blogs/blog-update.html'
    success_message = 'Post updated successfully!'

    def get_object(self):
        slug = self.kwargs.get('title_slug')
        return get_object_or_404(BlogPost, slug=slug)


class PostDeleteView(SuccessMessageMixin, DeleteView):
    model = BlogPost
    template_name = 'blogs/blog-delete.html'
    success_message = 'Post deleted successfully!'
    success_url = "/"

    def get_object(self):
        slug = self.kwargs.get('title_slug')
        return get_object_or_404(BlogPost, slug=slug)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PostDeleteView, self).delete(request, *args, **kwargs)


class SearchView(View):
    def get(self, request, *args, **kwargs):
        queryset = BlogPost.objects.all()
        query = request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query)
            ).distinct()
        context = {
            'queryset': queryset,
            'query': query,
        }
        return render(request, 'blogs/search_result.html', context)


# ! Function Based View for UserPost
# def user_posts(request, username):
#     queryset = BlogPost.objects.filter(author__username=username)
#     return render(request, 'blogs/user-posts.html', {'queryset': queryset, 'username': username})


class UserPost(ListView):
    model = BlogPost
    template_name = 'blogs/user-posts.html'
    paginate_by = 3
    context_object_name = 'queryset'
    ordering = ['-updated_at', '-created_at']

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return BlogPost.objects.filter(author=user).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.kwargs.get('username')
        return context

blog/templates/blogs/blog-delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Post
{% endblock title %}
{% block content %}

<div class="container p-4">
    <form action="." method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h4 class="display-5">Are you sure you want to delete {{ target_post.title }} ?</h4>
        <input type="submit" class="btn btn-outline-danger" value="Delete">
        <a href="{% url 'blog:home' %}" class="btn btn-outline-secondary">Cancel</a>
    </form>
</div>

{% endblock content %}

blog/templates/blogs/blog-detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}

{% endblock title %}

{% block style %}

<style>
</style>

{% endblock style %}
{% block content %}

<div class="card my-3 w-75 mx-auto">
    <div class="card-body">
        <!-- ! messages -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success my-3">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        <!-- ! body -->
        <div class="row">
            <div class="col-2">
                <img src="{{ object.author.profile.image.url }}" alt="{{ object.author.profile.image.url }}"
                    class="detail-user-pic">
            </div>
            <div class="col-10 my-3">
                <div class="br">
                    <h5>{{ object.title }}
                    </h5>
                </div>

                {% if blog.created_at == blog.updated_at %}
                <small class="text-muted">Author: <a
                        href="{% url 'blog:user_posts' object.author.username %}">{{ object.author.username }}</a>,
                    posted {{ object.created_at|naturaltime }}</small>
                {% else %}
                <small class="text-muted">Author: <a
                        href="{% url 'blog:user_posts' object.author.username %}">{{ object.author.username }}</a>,
                    updated {{ object.updated_at|naturaltime }}</small>
                {% endif %}
            </div>
        </div>

        <!-- ! update & delete -->
        {% if object.author.username == user.username %}
        <div class="mb-3">
            <a href="{{  object.get_update_url }}" class="btn btn-success btn-sm p-1">Update</a>
            <a href="{{  object.get_delete_url }}" class="btn btn-danger btn-sm p-1">Delete</a> <br><br>
        </div>

        {% else %}
        {% endif %}

        <!-- ! content -->
        <img src="{{ object.image.url }}" class="image_in_list" alt="">
        <div class="br">
            <p>{{ object.content|safe }}</p>
        </div>

        <!-- ! comments and likes -->
        <div id="disqus_thread"></div>
        <script>

            /**
            *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
            *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
            /*
            var disqus_config = function () {
            this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
            this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
            };
            */
            (function () { // DON'T EDIT BELOW THIS LINE
                var d = document, s = d.createElement('script');
                s.src = 'https://localhost-8000-bmnrmupewq.disqus.com/embed.js';
                s.setAttribute('data-timestamp', +new Date());
                (d.head || d.body).appendChild(s);
            })();
        </script>
    </div>
</div>
<br>
{% endblock content %}

blog/templates/blogs/blog-form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Post
{% endblock title %}

{% block style %}
{{ form.media }}
{% endblock style %}
{% block content %}

<div class="container p-4">
    <form action="." method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-outline-success" value="Post">
    </form>
</div>

{% endblock content %}

blog/templates/blogs/blog-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Post
{% endblock title %}
{% block content %}

<div class="container p-4">
    <form action="." method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-outline-success btn-block" value="Update">
    </form>
</div>

{% endblock content %}

blog/templates/blogs/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% load humanize %}
Home
{% endblock title %}
{% block content %}

<div class="row">
    <div class="col-3">
        <div class="card my-3 latest-post">
            <div class="card-body">
                <div class="card-title">
                    <h5>Latest Posts</h5>
                </div>
                {% for blog in latest_post %}
                <div class="card-title my-1"><small><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></small>
                </div>
                <small class="text-secondary"> Posted {{ blog.created_at|naturaltime }}</small>
                {% if forloop.last %}
                <div class="py-1"></div>
                {% else %}
                <div class="border-bottom py-1"></div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-6">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success my-2">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% for blog in queryset %}
        <!-- ! main posts here -->
        <div class="card my-2" style="background-color:#fff;">
            <div class="row p-3">
                <!-- ! Meta data of post -->
                <div class="row">
                    <div class="col-2">
                        <img src="{{ blog.author.profile.image.url }}" alt="{{ blog.author.profile.image.url }}"
                            class="home-user-pic mx-3">
                    </div>
                    <div class="col-10">
                        <h5 style="margin-bottom:0px;"><a
                                href="{% url 'blog:blog_detail' blog.slug %}">{{ blog.title }}</a></h5>
                        {% if blog.created_at == blog.updated_at %}
                        <small class="text-muted">Author: <a
                                href="{% url 'blog:user_posts' blog.author.username %}">{{ blog.author.username }}</a>,
                            posted {{ blog.created_at|naturaltime }}</small>
                        {% else %}
                        <small class="text-muted">Author: <a
                                href="{% url 'blog:user_posts' blog.author.username %}">{{ blog.author.username }}</a>,
                            updated {{ blog.updated_at|naturaltime }}</small>
                        {% endif %}
                    </div>
                </div>
                <div class="col-8">
                    <!--  ! body of post -->
                    <div class="border-bottom my-1"></div>
                    <p> {{ blog.content |safe |truncatechars:250  }}
                        <a href="{{ blog.get_absolute_url }}">(more)</a>
                    </p>
                    <!-- <a href="{% url 'blog:blog_detail' blog.slug %}">read more</a> -->

                </div>
                <div class="col-4">
                    <img src="{{ blog.image.url }}" class="image_in_list mt-5" alt="">
                </div>
            </div>

        </div>
        <!-- ! end of main posts here -->

        {% endfor %}

        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a href="?page=1" class="page-link">First</a></li>
            <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
            </li>
            {% endif %}

            {% for page_num in page_obj.paginator.page_range %}
            {% if page_num == page_obj.number %}
            <li class="page-item active"><a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a></li>
            {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3'  %}
            <li class="page-item"><a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next  %}
            <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a></li>
            <li class="page-item"><a href="?page={{ page_obj.paginator.page_nums }}" class="page-link">Last</a>
                {% endif %}
        </ul>
        {% endif %}
    </div>
    <div class="col-3">
        <!-- search -->
        <div class="card my-4">
            <div class="card-body">
                <div class="card-title">Search blog</div>
                <form action="{% url 'blog:search_blog' %}">
                    {% csrf_token %}
                    <input type="text" class="form-control" name="q" placeholder="What are you looking for?">
                    <input type="submit" value="Search" class="btn btn-success btn-sm mt-3">
                </form>
            </div>
        </div>

        <!-- About author -->
        <div class="card">
            <img src="{% static 'img/admin.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Author</h5>
                <p class="card-text">I am a passionate software engineer. I write about Python, Django, JavaScript,
                    HTML, CSS ...</p>
                <a href="#" class="btn btn-primary">About</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

blog/templates/blogs/search_result.html
{% extends 'base.html' %}
{% load search_tags %}

{% block style %}
<style>
    .highlight {
        background-color: yellow;
    }
</style>
{% endblock style %}

{% block content %}
<div class="container bg-light w-100">
    <h2 class="display-6 border-bottom py-3">Results for <span id="search"> "{{ query }}"</span></h2>
    {% for post in queryset %}
    <div class="my-1">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"> <a class="link"
                        href="{{ post.get_absolute_url }}">{{ post.title|highlight_search:query }}</a>
                </h4>
                <p>{{ post.content|truncatechars:150|highlight_search:query }}</p>
            </div>

        </div>

    </div>
    {% endfor %}
</div>


{% endblock %}

blog/templates/blogs/user-posts.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% load humanize %}
Home
{% endblock title %}
{% block content %}

<div class="row">
    <div class="col-8 mx-auto">
        <div class="card profile mt-5">
            <div class="card-body">
                {% for blog in queryset %}
                {% if forloop.first %}
                <div class="row">
                    <div class="col-2">
                        <img class="profile-pic" src="{{ blog.author.profile.image.url }}">
                    </div>
                    <div class="col-6">
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-success my-3">
                            {{ message }}
                        </div>
                        {% endfor %}
                        {% endif %}

                        <h2 class="account-heading" style="font-weight:400;">{{ blog.author.username|title }} </h2>

                        {% if blog.author.profile.description == '' %}
                        <span></span>
                        {% else %}
                        <small>
                            <p class="text-secondary">{{ blog.author.profile.description }}</p>
                        </small>
                        {% endif %}
                    </div>

                    <div class="col-4">
                        <h4 class="border-bottom pb-2">Contacts:</h4>
                        <small class="text-secondary">
                            {% if blog.author.email != 'None' or user.email != '' %}
                            <i class="fa fa-envelope"> </i> &nbsp; <input type="text" class="profile-email"
                                value="{{ blog.author.email }}">
                            {% else %}
                            <span></span>
                            {% endif %}
                        </small><br>


                        <small class="text-secondary">
                            {% if blog.author.profile.facebook == '' %}
                            <span></span>
                            {% else %}
                            <i class="fab fa-facebook"> </i> &nbsp; <input class="profile-facebook" type="text"
                                value="{{ blog.author.profile.facebook }}">
                            {% endif %}
                        </small><br>

                        <small class="text-secondary">
                            {% if blog.author.profile.whatsapp == '' %}
                            <span></span>
                            {% else %}
                            <i class="fab fa-whatsapp"> </i> {{ blog.author.profile.whatsapp }}
                            {% endif %}
                        </small><br>
                    </div>
                </div>
                {% else %}
                <span></span>
                {% endif %}

                {% endfor %}
            </div>
        </div>
        <!-- ! User Posts Here! -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success my-2">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        <br>
        <div class="alert alert-secondary">
            {{ username|title }} posted {{ page_obj.paginator.count }} post(s)
        </div>


        {% for blog in queryset %}
        <div class="card my-2" style="background-color:#fff;">
            <div class="row p-3">
                <div class="col-8">
                    <h5><a href="{% url 'blog:blog_detail' blog.slug %}">{{ blog.title }}</a></h5>
                    {% if blog.created_at == blog.updated_at %}
                    <small class="text-muted"> <a
                            href="{% url 'blog:user_posts' blog.author.username %}">{{ blog.author.username }}</a>
                        {{ blog.created_at|naturaltime }}</small>
                    {% else %}
                    <small class="text-muted">Updated by {{ blog.author.username }}
                        {{ blog.updated_at|naturaltime }}</small>
                    {% endif %}
                    <div class="border-bottom my-1"></div>
                    <p>{{ blog.content | linebreaks | truncatechars:150 }}
                        <a href="{{ blog.get_absolute_url }}">(more)</a>
                    </p>
                    <!-- <a href="{% url 'blog:blog_detail' blog.slug %}">read more</a> -->
                </div>
                <div class="col-4">
                    <img src="{{ blog.image.url }}" class="image_in_list mt-5" alt="">
                </div>
            </div>

        </div>
        {% endfor %}
        <br> <br>
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a href="?page=1" class="page-link">First</a></li>
            <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
            </li>
            {% endif %}

            {% for page_num in page_obj.paginator.page_range %}
            {% if page_num == page_obj.number %}
            <li class="page-item active"><a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a></li>
            {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3'  %}
            <li class="page-item"><a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next  %}
            <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a></li>
            <li class="page-item"><a href="?page={{ page_obj.paginator.page_nums }}" class="page-link">Last</a>
                {% endif %}
        </ul>
        {% endif %}
    </div>
</div>

{% endblock content %}