blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, SearchView, UserPost
from django.conf import settings
from . import views
from django.conf.urls.static import static


app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('search-blog/', SearchView.as_view(), name='search_blog'),
    path('posts/<username>/', UserPost.as_view(), name='user_posts'),

    path('blog/create/', PostCreateView.as_view(),
         name='blog_create'),
    path('blog/<slug:title_slug>/', PostDetailView.as_view(), name='blog_detail'),

    path('blog/<slug:title_slug>/update/',
         PostUpdateView.as_view(), name='blog_update'),

    path('blog/<slug:title_slug>/delete/',
         PostDeleteView.as_view(), name='blog_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django2/urls.py
from django.conf.urls.static import static
from django.conf import settings
"""django2 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
    path('tinymce/', include('tinymce.urls')),

    path('settings/change-password/', auth_views.PasswordChangeView.as_view(
        template_name='users/change-password.html'), name='password_change'),

    path('settings/change-password-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/change-password-done.html'), name='password_change_done'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password-reset.html',
                                              email_template_name='users/password-reset-email.html',
                                              subject_template_name='users/password-reset-subject.txt'),
         name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password-reset-done.html'),
        name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password-reset-confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password-reset-complete.html'),
        name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.profile_update, name='profile_update'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class UserExtended(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_slug = models.SlugField(blank=True)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    description = models.TextField(blank=True, help_text="256 Characters only")
    facebook = models.CharField(blank=True, max_length=255)
    whatsapp = models.CharField(blank=True, max_length=255)

    def __str__(self):
        return f"{ self.user.username } Profile"

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile
from django import forms


class SignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UpdateUserForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'description', 'facebook', 'whatsapp']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from .forms import SignupForm, UpdateUserForm, UpdateProfileForm


def signup_view(request):
    signup_form = SignupForm(request.POST or None)
    if signup_form.is_valid():
        signup_form.save()
        username = signup_form.cleaned_data.get('username')
        messages.success(
            request, f'Account successfully created for {username}, please login!')
        return redirect('users:login')
    return render(request, 'users/sign_up.html', context={'form': signup_form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = authenticate(username=username,
                                password=form.cleaned_data.get('password'))
            if user is not None:
                login(request, user)
                messages.success(
                    request, f'You have been successfully logged in as {username}')
                return redirect('blog:home')
            else:
                messages.error(
                    request, 'There was an error in your password and email!')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', context={
        'form': form
    })


def logout_view(request):
    logout(request)
    messages.success(request, 'You have been successfully logged out!')
    return redirect('users:login')


def profile_view(request):
    return render(request, 'users/profile.html')


def profile_update(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        user_profile = UpdateProfileForm(
            request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and user_profile.is_valid():
            user_form.save()
            user_profile.save()
            messages.success(
                request, 'Your profile has been updated successfully')
            return redirect('users:profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        user_profile = UpdateProfileForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': user_profile
    }
    return render(request, 'users/update_profile.html', context)

users/templates/users/change-password-done.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container w-50 my-5 mx-auto">
    <div class="alert alert-success">
        Your password has been changed successfully
    </div>
    <a href="{% url 'blog:home' %}">Home</a>
</div>

{% endblock content %}

users/templates/users/change-password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="card w-50 mx-auto my-5">
        <div class="card-body">
            <h4 class="card-title">Change Password</h4>
            <form action="." method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Submit" class="btn btn-success">
                <a href="{% url 'blog:home' %}" class="btn btn-secondary">Cancel</a>

            </form>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign up</title>
    <link rel="stylesheet" href="{% static 'blogs/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blogs/mystyle.css' %}">
</head>

<body>

    <div class="container">
        <div class="centered-div">
            <div class="card" style="position:relative">
                <img src="{% static 'img/default.jpg' %}" class="user-logo" alt="user logo">
                <div class="card-body">
                    {% if messages %}
                    <div class="alert alert-success">
                        {% for message in messages %}
                        {{  message }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <h1 class="card-title border-bottom pb-3" style="font-weight:400;">Login</h1>
                    <form action="." method="POST">
                        {% csrf_token %}
                        {{ form|crispy  }}
                        <input type="submit" class="btn btn-success btn-block" value="submit">
                    </form>
                    <hr>
                    <small class="text-secondary"> Need an account ? <a
                            href="{% url 'users:signup' %}">Signup</a><br></small>
                    <small class="text-secondary"> Forgot password ? <a href="{% url 'password_reset' %}">Reset
                            password</a></small>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Logout</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body>
    <div class="alert alert-info my-3 w-50 mx-auto">
        You have been successfully log out! <br>
        <a href="{% url 'users:login' %}">login again</a>
    </div>
</body>

</html>

users/templates/users/password-reset-complete.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign up</title>
    <link rel="stylesheet" href="{% static 'blogs/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blogs/mystyle.css' %}">
</head>

<body>
    <div class="container w-50 my-5 mx-auto">
        <div class="alert alert-success">
            Your password has been reset successfully
        </div>
        <a href="{% url 'users:login' %}" class="btn btn-secondary btn-sm">Cancel</a>
    </div>
</body>

</html>

users/templates/users/password-reset-confirm.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <link rel="stylesheet" href="{% static 'blogs/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blogs/mystyle.css' %}">
</head>

<body>

    <div class="container">
        <form action="." method="POST">
            <h2 class="display-4">Reset Password</h2>
            {% csrf_token %}
            {{ form|crispy  }}
            <input type="submit" class="btn btn-success btn-block" value="submit">
            <a href="{% url 'users:login' %}" class="btn btn-secondary">Cancel</a>

        </form>
    </div>
</body>

</html>

users/templates/users/password-reset-done.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign up</title>
    <link rel="stylesheet" href="{% static 'blogs/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blogs/mystyle.css' %}">
</head>

<body>
    <div class="container w-50 my-5 mx-auto">
        <div class="alert alert-success">
            An email has been sent with instruction to reset your password
        </div>
        <a href="{% url 'users:login' %}" class="btn btn-secondary btn-sm">Go back</a>
    </div>
</body>

</html>

users/templates/users/password-reset-email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

Basir Payenda

users/templates/users/password-reset.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign up</title>
    <link rel="stylesheet" href="{% static 'blogs/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blogs/mystyle.css' %}">
</head>

<body>

    <div class="container">
        <form action="." class="my-5 mx-auto w-50" method="POST">
            <h2 class="display-4">Reset Password</h2>
            {% csrf_token %}
            {{ form|crispy  }}
            <input type="submit" class="btn btn-success" value="submit">
            <a href="{% url 'users:login' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</body>

</html>

users/templates/users/profile.html
{% extends "base.html" %}

{% block content %}

<div class="card profile mt-5">
    <div class="card-body">
        <div class="row">
            <div class="col-2">
                <img class="profile-pic" src="{{ user.profile.image.url }}">
            </div>
            <div class="col-6">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success my-3">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}

                <h2 class="account-heading">{{ user.username }} </h2>

                {% if user.profile.description == '' %}
                <i class="fa fa-person"></i> <a href="{% url 'users:profile_update' %}"> Add
                    description</a>
                {% else %}
                <small>
                    <p class="text-secondary">{{ user.profile.description }}</p>
                </small>
                {% endif %}

                <a href="{% url 'users:profile_update' %}" class="btn btn-outline-success">Update</a>

            </div>
            <div class="col-4">
                <h4 class="border-bottom pb-2">Contacts:</h4>
                <small class="text-secondary">
                    {% if user.email != 'None' or user.email != '' %}
                    <i class="fa fa-envelope"> </i> &nbsp; <input type="text" class="profile-email"
                        value="{{ user.email }}">
                    {% else %}
                    <i class="fa fa-envelope"> </i> <a href="{% url 'users:profile_update' %}"> Add
                        email</a>
                    {% endif %}
                </small><br>

                <small class="text-secondary">
                    {% if user.profile.facebook == '' %}
                    <i class="fab fa-facebook"> </i> <a href="{% url 'users:profile_update' %}"> Add
                        Facebook</a>
                    {% else %}
                    <i class="fab fa-facebook"> </i> &nbsp; <input type="text" class="profile-facebook"
                        value="{{ user.profile.facebook }}">
                    {% endif %}
                </small><br>

                <small class="text-secondary">
                    {% if user.profile.whatsapp == '' %}
                    <i class="fab fa-whatsapp"> </i> <a href="{% url 'users:profile_update' %}">
                        Add Whatsapp</a>
                    {% else %}
                    <i class="fab fa-whatsapp"> </i> {{ user.profile.whatsapp }}
                    {% endif %}
                </small><br>
                <!-- <small>
                    <i class="fab fa-facebook"> </i> {{ user.profile.facebook }}
                </small><br>
                <small>
                    <i class="fab fa-whatsapp"> </i> {{ user.profile.whatsapp }}
                </small> -->

            </div>
        </div>
    </div>
</div>



{% endblock content %}

users/templates/users/sign_up.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign up</title>
    <link rel="stylesheet" href="{% static 'blogs/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blogs/mystyle.css' %}">
</head>

<body>

    <div class="container">
        <div class="centered-div sign-up-form">
            <div class="card" style="position:relative">
                <img src="{% static 'img/default.jpg' %}" class="user-logo" alt="user logo">
                <div class="card-body">
                    <h1 class="card-title border-bottom pb-3" style="font-weight:400;">Create an account</h1>
                    <form action="." method="POST">
                        {% csrf_token %}
                        {{ form|crispy  }}
                        <input type="submit" class="btn btn-success btn-block" value="submit">
                    </form>
                    <hr>
                    <small class="text-secondary"> Already have an account ? <a
                            href="{% url 'users:login' %}">Login</a><br></small>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

users/templates/users/update_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Update Profile
{% endblock title %}

{% block style %}

<style>
    footer {
        display: none;
    }
</style>
{% endblock style %}


{% block content %}

<div class="wrapper w-75 my-3 profile">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success my-3">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    <div class="card p-4">
        <!-- <h2 class="dispaly-5">Update Information</h2> -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
                <legend class="border-bottom pb-3 mb-3">Update Profile</legend>
                {{ user_form|crispy }}
                {{ profile_form|crispy }}
            </fieldset>
            <button class="btn btn-danger" type="submit">Update</button>
        </form>
    </div>
</div>
{% endblock content %}